{{{ include("controllers/oar-summary.js") }}}

{{{ include("models/oar-summary.js") }}}
{{{ include("models/oar-summary-grid.js") }}}
{{{ include("models/oar-summary-grid-const.js") }}}
{{{ include("models/oar-summary-grid-config.js") }}}
{{{ include("models/summary-line-bar-chart-const.js") }}}
{{{ include("models/summary-line-bar-chart-config.js") }}}
{{{ include("models/summary-pie-chart.js") }}}

{{{ include("services/oar-summary.js") }}}
{{{ include("services/oar-summary-translator.js") }}}

{{{ include("data/grid-mock-data.js") }}}
