{{{ include("../js/controllers/bdgt-mastercharts.js") }}}
{{{ include("controllers/bdgt-mastercharts-spec.js") }}}

{{{ include("../js/models/mastercharts-dialogs.js") }}}
{{{ include("models/mastercharts-dialogs-spec.js") }}}

{{{ include("../js/models/mastercharts-notifications.js") }}}
{{{ include("models/mastercharts-notifications-spec.js") }}}

{{{ include("../js/models/mastercharts-list-actions-def.js") }}}
{{{ include("models/mastercharts-list-actions-defs-spec.js") }}}

{{{ include("../js/models/mastercharts-list-config.js") }}}
{{{ include("models/mastercharts-list-config-spec.js") }}}

{{{ include("../js/models/mastercharts-list.js") }}}
{{{ include("models/mastercharts-list-spec.js") }}}

{{{ include("../js/models/mastercharts-list-actions.js") }}}
{{{ include("models/mastercharts-list-actions-spec.js") }}}

//mastercharts-grid-factory-spec
{{{ include("../js/models/mastercharts-grid-factory.js") }}}
{{{ include("models/mastercharts-grid-factory-spec.js") }}}


//masterchart-spec
{{{ include("../js/services/mastercharts.js") }}}
{{{ include("services/masterchart-spec.js") }}}