{{{ include("templates/templates.inc.js") }}}
{{{ include("services/market-rent.js") }}}
{{{ include("models/market-rent.js") }}}
{{{ include("models/market-rent-edit.js") }}}
{{{ include("models/market-rent-config.js") }}}
{{{ include("models/market-rent-calc.js") }}}
{{{ include("models/market-rent-detail-calc.js") }}}
{{{ include("models/market-rent-setting.js") }}}
{{{ include("models/change-rent.js") }}}
{{{ include("models/market-rent-table-config.js") }}}
{{{ include("controllers/market-rent.js") }}}

{{{ include("services/market-rent-reference.js") }}}
{{{ include("models/market-rent-reference-config.js") }}}
{{{ include("controllers/market-rent-reference.js") }}}

{{{ include("models/market-rent-unit-student-config.js") }}}
{{{ include("controllers/market-rent-unit-student.js") }}}

{{{ include("models/market-rent-unittype-student-config.js") }}}
{{{ include("controllers/market-rent-unittype-student.js") }}}


{{{ include("models/market-rent-unittype-svcgroup-config.js") }}}
{{{ include("controllers/market-rent-unittype-svcgroup.js") }}}

{{{ include("models/market-rent-unittype-program-config.js") }}}
{{{ include("controllers/market-rent-unittype-program.js") }}}


{{{ include("models/mkrent-byunit-config.js") }}}
{{{ include("controllers/market-rent-byunit.js") }}}


{{{ include("models/mkrent-byunit-type-config.js") }}}
{{{ include("controllers/market-rent-byunit-type.js") }}}


{{{ include("models/market-rent-profarma-config.js") }}}
{{{ include("controllers/market-rent-profarma.js") }}}

{{{ include("models/form-config.js") }}}
{{{ include("models/market-rent-error-handling.js") }}}
{{{ include("models/market-rent-summary-calc.js") }}}

{{{ include("services/market-rent-comments.js") }}}
{{{ include("models/market-rent-comments.js") }}}

{{{ include("models/actual-rent-cap-validation.js") }}}

{{{ include("models/change-rent-mr-ar.js") }}}

