angular.module('budgeting').run(['$templateCache', function($templateCache) {
$templateCache.put("rentalincome/marketrent/templates/mktrent-comment-count.html",
"<a class=\"rp-cg-text rp-cg-body-text\" ng-click=\"column.config.makeRentComment(column)\" ng-class=\"{'comment-cell' : column.row.data.commentCount > 0}\"><i class=\"rp-icon-chat-bubble\"></i> {{column.row.data.commentCount}}</a>");
$templateCache.put("rentalincome/marketrent/templates/mktrent-editable.html",
"<div class=\"rp-cg-editable\"><span class=\"rp-cg-text rp-cg-body-text mr-lable\">{{column.getVal().toLocaleString()}}</span><!--<span class=\"rp-cg-text\" ng-if=\"column.row.data.leaseExpirePeriod == column.config.key.replace('period','')\" title=\"Lease expires : {{column.row.data.leaseExpireDate}}\">\n" +
"        *\n" +
"    </span>--><div ng-class=\"{'error-left': column.row.data.leaseExpirePeriod == column.config.key.replace('period','')}\"><input class=\"rp-cg-input-text rp-form-input text-right mr-text\" ng-model-options=\"{updateOn: 'blur'}\" ng-change=\"column.config.makeRentVal(column.config, model.gridData,column)\" ng-focus=\"column.config.makeRentFocus(column.config, column)\" ng-model=\"column.row.data[column.config.key]\"><!--ng-pattern=\"/^[0-9]+(\\.[0-9]{1,2})?$/\"--><!--onkeypress='return event.charCode >= 48 && event.charCode <= 57'--></div></div>");
$templateCache.put("rentalincome/marketrent/templates/mktrent-grp-comment-count.html",
"<a class=\"rp-cg-text rp-cg-body-text\" ng-click=\"column.config.makeRentComment(column)\" ng-class=\"{'comment-cell' : column.row.data.commentCount > 0}\" ng-if=\"column.row.data.rowType ==='groupHeader'\"><i class=\"rp-icon-chat-bubble\"></i> {{column.row.data.commentCount}}</a>");
$templateCache.put("rentalincome/marketrent/templates/mktrent-proforma-unit.html",
"<div class=\"rp-cg-editable\"><input ng-if=\"column.row.data.isProformaUnitType > 0\" class=\"rp-cg-input-text rp-form-input text-right mr-text\" ng-model-options=\"{updateOn: 'blur'}\" ng-change=\"column.config.updateUnitCount()\" ng-model=\"column.row.data[column.config.key]\" onkeypress=\"return event.charCode >= 48 && event.charCode <= 57\"> <span ng-if=\"column.row.data.isProformaUnitType > 0\" class=\"rp-cg-text rp-cg-body-text mr-lable\">{{column.row.data.unitCount }}</span></div><span class=\"rp-cg-text rp-cg-body-text\" ng-if=\"column.row.data.isProformaUnitType < 1\">{{column.row.data.unitCount }}</span>");
$templateCache.put("rentalincome/marketrent/templates/mktrent-proforma.html",
"<div class=\"rp-cg-row-header\"><div class=\"rp-cg-text rp-cg-body-text\" ng-if=\"column.row.data && column.row.data.isProformaUnitType < 1\"><span>{{column.row.data.name}}</span><!--<span class=\"comment-cell\"><i class=\"rp-icon-chat-bubble\"></i> {{column.row.data.commentCount}}</span>--></div><div class=\"rp-cg-text rp-cg-body-text col-md-12 p-l-0\" ng-if=\"column.row.data && column.row.data.isProformaUnitType > 0\"><div class=\"mr-text\"><span ng-click=\"column.config.removeUnitType(column)\" class=\"remove-icon pull-left m-r-sm p-t-xs\"><i class=\"rp-del-icon\"></i></span> <input class=\"rp-cg-input-text rp-form-input visible-sm-inline-block\" ng-model-options=\"{updateOn: 'blur'}\" ng-change=\"column.config.validateDescr(column)\" ng-model=\"column.row.data[column.config.key]\"></div><div class=\"mr-lable\"><span>{{column.row.data.name}}</span></div><!--<span class=\"comment-cell\"><i class=\"rp-icon-chat-bubble\"></i> {{column.row.data.commentCount}}</span>--></div></div>");
$templateCache.put("rentalincome/marketrent/templates/mktrent-service-unit-editable.html",
"<div class=\"rp-cg-editable\"><span class=\"rp-cg-text rp-cg-body-text mr-lable\">{{column.getVal().toLocaleString()}}</span><div ng-class=\"{'error': column.row.data.serviceGroupID > 0 && (column.row.data.grpBalUnitCount < 0) && (column.row.data.currrentGrp === column.row.data.serviceGroupID)}\"><input class=\"rp-cg-input-text rp-form-input text-right mr-text\" ng-focus=\"column.config.makeRentCountFocus(column.config, column)\" ng-disabled=\"column.row.data.serviceGroupID < 1 ? true : false\" ng-model-options=\"{updateOn: 'blur'}\" title=\"{{column.row.data.title}}\" ng-change=\"column.config.makeRentUnitVal(column.config, model,column)\" ng-model=\"column.row.data[column.config.key]\" onkeypress=\"return event.charCode >= 48 && event.charCode <= 57\"></div></div>");
$templateCache.put("rentalincome/marketrent/templates/mktrent-stud-aptsbeds.html",
"<div class=\"rp-cg-row-header\"><div class=\"rp-cg-text rp-cg-body-text\"><span class=\"apts-beds-cell text-right\" ng-if=\"column.row.data.rowType === 'groupHeader' \">{{column.row.data.aparetmentCount}}/{{column.row.data.bedCount}}</span></div></div>");
$templateCache.put("rentalincome/marketrent/templates/mktrent-stud-gpheader.html",
"<div class=\"rp-cg-row-header\"><div class=\"rp-cg-text rp-cg-body-text\"><i ng-class=\"{'rp-angleDown':!row.state.open, 'rp-angleUp':row.state.open}\"></i> <span>{{column.row.data.rowTitle}} ({{column.row.data.bedCount}})</span><!--<span class=\"comment-cell\"><i class=\"rp-icon-chat-bubble\"></i> {{column.row.data.commentCount}}</span>--></div></div>");
$templateCache.put("rentalincome/marketrent/templates/mktrent-stud-servicegrpheader.html",
"<div class=\"rp-cg-row-header\"><div class=\"rp-cg-text rp-cg-body-text\"><i ng-class=\"{'rp-angleDown':!row.state.open, 'rp-angleUp':row.state.open}\"></i> <span class=\"p-l-sm\">{{column.row.data.rowTitle}}</span><!--<span class=\"comment-cell\"><i class=\"rp-icon-chat-bubble\"></i> {{column.row.data.commentCount}}</span>--></div></div>");
$templateCache.put("rentalincome/marketrent/templates/mktrent-stud-unit-type-grpheader.html",
"<div class=\"rp-cg-row-header\"><div class=\"rp-cg-text rp-cg-body-text\"><!--<i ng-class=\"{'rp-angleDown':!row.state.open, 'rp-angleUp':row.state.open}\"></i>--><span>{{column.row.data.rowTitle}}</span><!--<span class=\"comment-cell\"><i class=\"rp-icon-chat-bubble\"></i> {{column.row.data.commentCount}}</span>--></div></div>");
$templateCache.put("rentalincome/marketrent/templates/mktrent-total-change.html",
"<div class=\"rp-cg-editable\"><span class=\"rp-cg-text rp-cg-body-text\">{{column.config.makeRentVal(column.config, model.gridData)}}</span><!--<div class=\"rp-input-text small\">\n" +
"        <input class=\"rp-cg-input-text rp-form-input\"\n" +
"               ng-model-options=\"{updateOn: 'blur'}\"\n" +
"               ng-change=\"column.config.makeRentVal(column.config, model.gridData)\"\n" +
"               ng-model=\"column.row.data[column.config.key]\" />\n" +
"    </div>--></div>");
$templateCache.put("rentalincome/marketrent/templates/mktrent-total.html",
"<div class=\"rp-cg-editable\"><span class=\"rp-cg-text toggle-text text-right total\" title=\"{{column.row.data.total | number}}\">{{column.row.data.total | number}}</span> <span class=\"rp-cg-text toggle-text text-right total\" ng-if=\"column.row.data.total.indexOf('%') > 0  \" title=\"{{column.row.data.total}}\">{{column.row.data.total}}</span></div>");
$templateCache.put("rentalincome/marketrent/templates/mktrent-unit-chaticon.html",
"<div class=\"rp-cg-row-header\"><div class=\"rp-cg-text rp-cg-body-text\"><span>{{column.row.data.unitNumber}}</span><!--<span class=\"comment-cell\"><i class=\"rp-icon-chat-bubble\"></i> {{column.row.data.commentCount}}</span>--></div></div>");
$templateCache.put("rentalincome/marketrent/templates/mktrent-unit-type-desription.html",
"<div class=\"rp-cg-row-header\"><div class=\"rp-cg-text rp-cg-body-text\"><span class=\"text-ellipsis\" title=\"{{column.row.data.unitTypeDescription}} ({{column.row.data.floorPlan}})\">{{column.row.data.unitTypeDescription}} ({{column.row.data.floorPlan}})</span><!--<span class=\"comment-cell\"><i class=\"rp-icon-chat-bubble\"></i> {{column.row.data.commentCount}}</span>--></div></div>");
$templateCache.put("rentalincome/marketrent/templates/mktrent-unittype-chaticon.html",
"<div class=\"rp-cg-row-header\"><div class=\"rp-cg-text rp-cg-body-text\"><span>{{column.row.data.description}}</span><!--<span class=\"comment-cell\"><i class=\"rp-icon-chat-bubble\"></i> {{column.row.data.commentCount}}</span>--></div></div>");
$templateCache.put("rentalincome/marketrent/templates/mktrent-unittype-program.html",
"<div class=\"rp-cg-row-header\"><div class=\"rp-cg-text rp-cg-body-text\"><span>{{column.row.data.rowTitle}}</span> <span ng-class=\"{'comment-cell' : column.row.data.commentCount > 0}\"><i class=\"rp-icon-chat-bubble\"></i> {{column.row.data.commentCount}}</span></div></div>");
$templateCache.put("rentalincome/marketrent/templates/mktrent-unittype-servicegroup.html",
"<div class=\"rp-cg-row-header\"><div class=\"rp-cg-text rp-cg-body-text\"><span>{{column.row.data.rowTitleUnitCalculation}}</span> <span class=\"\" ng-class=\"{'comment-cell' : column.row.data.commentCount > 0}\"><i class=\"rp-icon-chat-bubble\"></i> {{column.row.data.commentCount}}</span></div></div>");
$templateCache.put("rentalincome/marketrent/templates/mktrentunit-editable.html",
"<div class=\"rp-cg-editable\"><span class=\"rp-cg-text rp-cg-body-text mr-lable\">{{column.getVal().toLocaleString()}}</span><div ng-class=\"{'error': column.row.data.programID > 0 && (column.row.data.grpBalUnitCount < 0) && (column.row.data.currrentGrp === column.row.data.programID)}\"><input class=\"rp-cg-input-text rp-form-input text-right mr-text\" ng-focus=\"column.config.makeRentCountFocus(column.config, column)\" ng-disabled=\"column.row.data.programID < 1 ? true : false\" ng-model-options=\"{updateOn: 'blur'}\" title=\"{{column.row.data.title}}\" ng-change=\"column.config.makeRentUnitVal(column.config, model,column)\" ng-model=\"column.row.data[column.config.key]\" onkeypress=\"return event.charCode >= 48 && event.charCode <= 57\"></div></div>");
$templateCache.put("rentalincome/marketrent/templates/profarma-title.html",
"<div class=\"rp-cg-editable\"><span class=\"rp-cg-text rp-cg-body-text mr-lable\">{{column.getVal().toLocaleString()}}</span> <i class=\"rp-icon-delete\"></i> <input class=\"rp-cg-input-text rp-form-input mr-text\" ng-model-options=\"{updateOn: 'blur'}\" ng-model=\"column.row.data[column.config.key]\"></div>");
$templateCache.put("rentalincome/marketrent/templates/rent-title.html",
"<span class=\"rp-cg-text rp-cg-body-text m-l-md\">{{column.getVal()}}</span>");
}]);
