{{{ include("../../../_common/standalone/js/directives/currency-editable.js") }}}

{{{ include("controllers/occupancy.js") }}}

{{{ include("models/asset-type.js") }}}
{{{ include("models/occupancy-2.js") }}}
{{{ include("models/occupancy-options.js") }}}
{{{ include("models/occupancy-form-config.js") }}}
{{{ include("models/occupancy-goal-percent.js") }}}
{{{ include("models/occupancy-goal-type.js") }}}
{{{ include("models/occupancy-method.js") }}}
{{{ include("models/open-period-ref-data.js") }}}
{{{ include("models/rent-loss-method.js") }}}
{{{ include("models/unit-loss-type.js") }}}

{{{ include("services/occupancy.js") }}}
{{{ include("services/translator.js") }}}
{{{ include("services/validator.js") }}}
	