//  Tasks Module

//  Templates

{{{ include("templates/tasks-module.js") }}}
{{{ include("templates/tasks-carousel.js") }}}
{{{ include("templates/tasks-selection-list.js") }}}
{{{ include("templates/task.js") }}}

//  Services

{{{ include("services/draggable-touch.js") }}}
{{{ include("services/draggable.js") }}}
{{{ include("services/task-manager.js") }}}
{{{ include("services/task-touch.js") }}}
{{{ include("services/task.js") }}}
{{{ include("services/tasks.js") }}}
{{{ include("services/workspace.js") }}}




//  Controllers

{{{ include("controllers/tasks-module.js") }}}

//  Directives

{{{ include("directives/tasks-module.js") }}}
{{{ include("directives/tasks-carousel.js") }}}
{{{ include("directives/task-selection-list.js") }}}
{{{ include("directives/tasks-carousel-slider.js") }}}
{{{ include("directives/tasks-carousel-screen.js") }}}
{{{ include("directives/task.js") }}}
