{{{ include('controllers\occupancy-service-group.js') }}}

{{{ include('models\service-group-constant.js') }}}
{{{ include('models\service-group-content.js') }}}
{{{ include('models\service-group-grid-config.js') }}}
{{{ include('models\service-group-mapper.js') }}}
{{{ include('models\service-group.js') }}}
{{{ include('models\service-gruop-mock.js') }}}
{{{ include('services\service-group.js') }}}
{{{ include('models\service-grid-option-config.js') }}}
{{{ include('templates\templates.inc.js') }}}
{{{ include('models\table-settings.js') }}}
