{{{ include('controllers\service-group.js') }}}

{{{ include('models\service-group-constant.js') }}}
{{{ include('models\service-group-content.js') }}}
{{{ include('models\service-group-grid-config.js') }}}
{{{ include('models\service-group-mapper.js') }}}
{{{ include('models\service-group.js') }}}

{{{ include('models\service-group-calculations.js') }}}
{{{ include('models\service-group-settings.js') }}}
{{{ include('models\service-group-data.js') }}}
{{{ include('models\service-comment-svc.js') }}}

{{{ include('models\service-grid-option-config.js') }}}
{{{ include('models\service-group-mock.js') }}}
{{{ include('services\service-group.js') }}}

{{{ include('templates\templates.inc.js') }}}