angular.module('budgeting').run(['$templateCache', function($templateCache) {
$templateCache.put("occupancy-renewals/occupancy-vacancy-worksheet/templates/occupancy-goal-percentage.html",
"<div class=\"rp-cg-text rp-cg-body-text text-left rp-cg-editable\">{{column.row.data[column.config.key] }} <span ng-if=\"model.isEditable\" class=\"text-right p-l-1 display-occupancy-goal\"><input class=\"rp-cg-input-text rp-form-input\" ng-model-options=\"{updateOn: 'blur' }\" ng-change=\"column.config.action.change(column, row)\" ng-blur=\"column.config.action.blur(column, row)\" ng-model=\"column.row.data.goalPercentage\"></span></div>");
$templateCache.put("occupancy-renewals/occupancy-vacancy-worksheet/templates/occupancy-update-column.html",
"<div class=\"rp-cg-text rp-cg-body-text text-left\">{{column.row.data[column.config.key] }} <span class=\"text-right text-primary pull-right\" ng-if=\"model.isEditable\"><a ng-click=\"column.config.action.click(column, row)\">Update</a> <span class=\"rp-icon-question-circle p-l-sm\" ng-click=\"column.config.action.onIconClick(column, row)\"></span></span><div class=\"col-sm-3 fdn-arrow box-color text-color begining-help-text tool-tip-product\" ng-show=\"column.row.data.updateBOUToolTip\"><span class=\"arrow top pull-left white\"></span><div class=\"box-body\">{{column.row.data.helpText}}</div></div></div>");
$templateCache.put("occupancy-renewals/occupancy-vacancy-worksheet/templates/reference-data-header.html",
"<div class=\"rp-cg-text rp-cg-body-text\"><span class=\"ft-s-14 _600\">{{column.row.data[column.config.key] }}</span><div class=\"ft-s-10 text-neutral-03\">{{column.config.data.refBudgetYear }} Actuals</div></div><div class=\"m-t-1 ft-s-10 refText\"><i class=\"m-r-xs rp-icon-info-circle ft-s-10\"></i> 2016 Budget data will be loaded into the open period starting from JAN-2016</div>");
$templateCache.put("occupancy-renewals/occupancy-vacancy-worksheet/templates/update-begining-units.html",
"<table><tr><td style=\"font-size: 12pt; font-weight: bold\">Update beginning occupied <span style=\"font-size: 12pt; font-weight: bold\">{{modal.content.beginingUnits}}</span></td></tr><tr><td style=\"height: 25px\"></td></tr><tr><td style=\"font-style: italic\">The \"Beginning occupied <span style=\"font-style: italic\">{{modal.content.beginingUnits}}</span>\" for the first period is considered to be the \"ending\" occupied number of <span style=\"font-style: italic\">{{modal.content.beginingUnits}}</span> for the year before this budget year. This gives us a starting point to calculate the \"Ending occupied units\" after adjusting for move-ins and move-outs.</td></tr><tr><td style=\"height: 20px\"></td></tr><tr><td style=\"font-style: italic\">You may update this field from the current number of occupied <span style=\"font-style: italic\">{{modal.content.beginingUnits}}</span> for this property by clicking the \"Update\" button below. Click the \"Cancel\" button to leave this number unchanged and close this window.</td></tr><tr><td style=\"height: 20px\"></td></tr><tr><td style=\"text-align: center\">The current number of Occupied <span>{{modal.content.beginingUnits}}</span> is &nbsp; <span style=\"font-weight: bold\">{{modal.content.unitsCount}}</span></td></tr><tr><td style=\"height: 30px\"></td></tr></table>");
}]);
