{{{ include('controllers\payroll-taxes-insurance.js') }}}

{{{ include('models\payroll-taxes-insurance.js') }}}
{{{ include('models\payroll-taxes-insurance-content.js') }}}
{{{ include('models\payroll-taxes-insurance-mapper.js') }}}
{{{ include('models\payroll-taxes-insurance-constant.js') }}}
{{{ include('models\payroll-taxes-insurance-form-config.js') }}}
{{{ include('models\payroll-taxes-insurance-grid-config.js') }}}

{{{ include('templates\payroll-tax-insurance-type.js') }}}

{{{ include('services\payroll-taxes-insurance.js') }}}