//  SampleCg Service

(function (angular) {
    'use strict';

    function sumamryMock() {  
            var model={};

    model.getData=function(){      

        return {
                        "records": [
                            {
                                "rowType": "groupHeader",
                                "level": 1,
                                "groupID": 1,
                                "rowID": 1,
                                "rowClass": "income",
                                "columnTitle": "INCOME"
                            },
                            {
                                "rowType": "groupHeader",
                                "level": 2,
                                "groupID": 2,
                                "rowID": 2,
                                "rowClass": "accountCategory",
                                "columnTitle": "Gross Potential Rent"
                            },
                            {
                                "level": 2,
                                "groupID": 2,
                                "rowID": 3,
                                "rowClass": "glAccount",
                                "rowType": "editable",
                                "columnTitle": "4010.000 Rent",
			                    "firstReferenceRowYear" : 2014,
			                    "firstReferenceRowType" : "2014 Actual",
			                    "firstReferenceRowValue" : 70000,
			                    "currentModelYear" : 2015,
			                    "currentModelType" : "2015 Budget",
			                    "currentModelValue" : 70000,
			                    "percentageVariance" : "0%",
			                    "dollerVariance" : 0,
			                    "perUnit" : 11000,
			                    "PerSqFt" : 500,
			                    "rollingNoOfPeriods" : 12,
			                    "rollingNoOfPeriodsValue" : 10000,
			                    "commentCount" : 0,
			                    "hasReviewerComment": true,
			                    "hasReferenceData" : true
		                    },
                            {
                                "level": 2,
                                "groupID": 2,
                                "rowID": 4,
                                "rowClass": "glAccount",
                                "rowType": "editable",
                                "columnTitle": "4020.000 Rent",
                                "firstReferenceRowYear" : 2014,
			                    "firstReferenceRowType" : "2014 Actual",
			                    "firstReferenceRowValue" : 80000,
			                    "currentModelYear" : 2015,
			                    "currentModelType" : "2015 Budget",
			                    "currentModelValue" : 80000,
			                    "percentageVariance" : "0%",
			                    "dollerVariance" : 0,
			                    "perUnit" : 11000,
			                    "PerSqFt" : 500,
			                    "rollingNoOfPeriods" : 12,
			                    "rollingNoOfPeriodsValue" : 8000,
			                    "commentCount" : 0,
			                    "hasReviewerComment": true,
			                    "hasReferenceData" : true
                            },
                            {
                                "level": 2,
                                "groupID": 2,
                                "rowID": 5,
                                "rowClass": "glAccount",
			                    "rowType": "editable",
                                "columnTitle": "4030.000 Corporate Suite Income",
                                "firstReferenceRowYear" : 2014,
			                    "firstReferenceRowType" : "2014 Actual",
			                    "firstReferenceRowValue" : 90000,
			                    "currentModelYear" : 2015,
			                    "currentModelType" : "2015 Budget",
			                    "currentModelValue" : 90000,
			                    "percentageVariance" : "0%",
			                    "dollerVariance" : 0,
			                    "perUnit" : 11000,
			                    "PerSqFt" : 500,
			                    "rollingNoOfPeriods" : 12,
			                    "rollingNoOfPeriodsValue" : 7000,
			                    "commentCount" : 2,
			                    "hasReviewerComment": true,
			                    "hasReferenceData" : true
                            },
                            {
                                "level": 2,
                                "groupID": 2,
                                "rowID": 6,
                                "rowClass": "glAccount",
			                    "rowType": "editable",
                                "columnTitle": "4020.000 Corporate Suite Income",
                                "firstReferenceRowYear" : 2014,
			                    "firstReferenceRowType" : "2014 Actual",
			                    "firstReferenceRowValue" : 87820,
			                    "currentModelYear" : 2015,
			                    "currentModelType" : "2015 Budget",
			                    "currentModelValue" : 56230,
			                    "percentageVariance" : "0%",
			                    "dollerVariance" : 0,
			                    "perUnit" : 11000,
			                    "PerSqFt" : 500,
			                    "rollingNoOfPeriods" : 12,
			                    "rollingNoOfPeriodsValue" : 600,
			                    "commentCount" : 2,
			                    "hasReviewerComment": true,
			                    "hasReferenceData" : true
                            },
                            {
                                "level": 2,
                                "groupID": 2,
                                "rowID": 7,
                                "rowClass": "glAccount",
			                    "rowType": "editable",
                                "columnTitle": "4020.000 Corporate Suite Income",
                                "firstReferenceRowYear" : 2014,
			                    "firstReferenceRowType" : "2014 Actual",
			                    "firstReferenceRowValue" : 4000,
			                    "currentModelYear" : 2015,
			                    "currentModelType" : "2015 Budget",
			                    "currentModelValue" : 6000,
			                    "percentageVariance" : "0%",
			                    "dollerVariance" : 0,
			                    "perUnit" : 11000,
			                    "PerSqFt" : 500,
			                    "rollingNoOfPeriods" : 12,
			                    "rollingNoOfPeriodsValue" : 73200,
			                    "commentCount" : 2,
			                    "hasReviewerComment": true,
			                    "hasReferenceData" : true
                            },
                            {
                                "level": 2,
                                "groupID": 2,
                                "rowID": 8,
                                "rowClass": "glAccount",
			                    "rowType": "total",
                                "columnTitle": "Total Gross Potential Rent",
                                "firstReferenceRowYear" : 2014,
			                    "firstReferenceRowType" : "2014 Actual",
			                    "firstReferenceRowValue" : 70000,
			                    "currentModelYear" : 2015,
			                    "currentModelType" : "2015 Budget",
			                    "currentModelValue" : 70000,
			                    "percentageVariance" : "0%",
			                    "dollerVariance" : 0,
			                    "perUnit" : 11000,
			                    "PerSqFt" : 500,
			                    "rollingNoOfPeriods" : 12,
			                    "rollingNoOfPeriodsValue" : 10000,
			                    "commentCount" : 2,
			                    "hasReviewerComment": true,
			                    "hasReferenceData" : true
                            },
                            {
                                "rowType": "groupHeader",
                                "level": 2,
                                "groupID": 3,
                                "rowID": 9,
                                "rowClass": "accountCategory",
                                "columnTitle": "Rental Losses"
                            },
                            {
                                "level": 2,
                                "groupID": 3,
                                "rowID": 10,
                                "rowClass": "glAccount",
			                    "rowType": "editable",
                                "columnTitle": "4400.00 Bad Debt Recovery",
                                "firstReferenceRowYear" : 2014,
			                    "firstReferenceRowType" : "2014 Actual",
			                    "firstReferenceRowValue" : 70000,
			                    "currentModelYear" : 2015,
			                    "currentModelType" : "2015 Budget",
			                    "currentModelValue" : 70000,
			                    "percentageVariance" : "0%",
			                    "dollerVariance" : 0,
			                    "perUnit" : 11000,
			                    "PerSqFt" : 500,
			                    "rollingNoOfPeriods" : 12,
			                    "rollingNoOfPeriodsValue" : 10000,
			                    "commentCount" : 2,
			                    "hasReviewerComment": false,
			                    "hasReferenceData" : true
                            },
                            {
                                "level": 2,
                                "groupID": 3,
                                "rowID": 11,
                                "rowClass": "glAccount",
			                    "rowType": "editable",
                                "columnTitle": "4510.000 Vacancy Loss",
                                "firstReferenceRowYear" : 2014,
			                    "firstReferenceRowType" : "2014 Actual",
			                    "firstReferenceRowValue" : 70000,
			                    "currentModelYear" : 2015,
			                    "currentModelType" : "2015 Budget",
			                    "currentModelValue" : 70000,
			                    "percentageVariance" : "0%",
			                    "dollerVariance" : 0,
			                    "perUnit" : 11000,
			                    "PerSqFt" : 500,
			                    "rollingNoOfPeriods" : 12,
			                    "rollingNoOfPeriodsValue" : 10000,
			                    "commentCount" : 2,
			                    "hasReviewerComment": true,
			                    "hasReferenceData" : true
                            },
                            {
                                "level": 2,
                                "groupID": 3,
                                "rowID": 12,
                                "rowClass": "glAccount",
			                    "rowType": "total",
                                "columnTitle": "Total Rental Losses",
                                "firstReferenceRowYear" : 2014,
			                    "firstReferenceRowType" : "2014 Actual",
			                    "firstReferenceRowValue" : 70000,
			                    "currentModelYear" : 2015,
			                    "currentModelType" : "2015 Budget",
			                    "currentModelValue" : 70000,
			                    "percentageVariance" : "0%",
			                    "dollerVariance" : 0,
			                    "perUnit" : 11000,
			                    "PerSqFt" : 500,
			                    "rollingNoOfPeriods" : 12,
			                    "rollingNoOfPeriodsValue" : 10000,
			                    "commentCount" : 2,
			                    "hasReviewerComment": false,
			                    "hasReferenceData" : true
                            },
                            {
                                "level": 1,
                                "groupID": 1,
                                "rowID": 13,
                                "rowClass": "total",
			                    "rowType": "total",
                                "columnTitle": "TOTAL INCOME",
                                "firstReferenceRowYear" : 2014,
			                    "firstReferenceRowType" : "2014 Actual",
			                    "firstReferenceRowValue" : 70000,
			                    "currentModelYear" : 2015,
			                    "currentModelType" : "2015 Budget",
			                    "currentModelValue" : 70000,
			                    "percentageVariance" : "0%",
			                    "dollerVariance" : 0,
			                    "perUnit" : 11000,
			                    "PerSqFt" : 500,
			                    "rollingNoOfPeriods" : 12,
			                    "rollingNoOfPeriodsValue" : 10000,
			                    "commentCount" : 2,
			                    "hasReviewerComment": true,
			                    "hasReferenceData" : true
                            },
                            {
                                "level": 1,
                                "groupID": 5,
                                "rowID": 14,
                                "rowClass": "total",
			                    "rowType": "total",
                                "columnTitle": "NET INCOME",
                                "firstReferenceRowYear" : 2014,
			                    "firstReferenceRowType" : "2014 Actual",
			                    "firstReferenceRowValue" : 70000,
			                    "currentModelYear" : 2015,
			                    "currentModelType" : "2015 Budget",
			                    "currentModelValue" : 70000,
			                    "percentageVariance" : "0%",
			                    "dollerVariance" : 0,
			                    "perUnit" : 11000,
			                    "PerSqFt" : 500,
			                    "rollingNoOfPeriods" : 12,
			                    "rollingNoOfPeriodsValue" : 10000,
			                    "commentCount" : 2,
			                    "hasReviewerComment": true,
			                    "hasReferenceData" : true
                            },
                            {
                                "level": 1,
                                "groupID": 6,
                                "rowID": 15,
                                "rowClass": "total",
			                    "rowType": "total",
                                "columnTitle": "NET CASH FLOW",
                                "firstReferenceRowYear" : 2014,
			                    "firstReferenceRowType" : "2014 Actual",
			                    "firstReferenceRowValue" : 70000,
			                    "currentModelYear" : 2015,
			                    "currentModelType" : "2015 Budget",
			                    "currentModelValue" : 70000,
			                    "percentageVariance" : "0%",
			                    "dollerVariance" : 0,
			                    "perUnit" : 11000,
			                    "PerSqFt" : 500,
			                    "rollingNoOfPeriods" : 12,
			                    "rollingNoOfPeriodsValue" : 10000,
			                    "commentCount" : 2,
			                    "hasReviewerComment": true,
			                    "hasReferenceData" : true
                            }
                        ]
                    };
            };

        return model;
    }

    angular
        .module('budgeting')
        .factory('sumamryMock', [sumamryMock]);
})(angular);
