


{{{ include("controllers/bdgt-manage-gl-account.js") }}}
{{{ include("services/manage-gl-account.js") }}}
{{{ include("models/manage-gl-account.js") }}}

{{{ include("models/manage-gl-actionslist.js") }}}
{{{ include("models/manage-gl-createupdategl.js") }}}
{{{ include("models/manage-gl-print.js") }}}
{{{ include("models/manage-grid.js") }}}
{{{ include("models/manage-gl-error-handling.js") }}}
{{{ include("models/manage-gl-grid-factory.js") }}}

//manage-gl-notifications
{{{ include("models/manage-gl-notifications.js") }}}
{{{ include("models/manage-gl-edit-save-gl.js") }}}

{{{ include("models/manage-gl-config.js") }}}

{{{ include("templates/manage-gl-budgetuse.js") }}}
{{{ include("templates/manage-gl-restrict-payroll.js") }}}
















