{{{ include('controllers\housing-allowance.js') }}}

{{{ include('models\housing-allowance.js') }}}
{{{ include('models\housing-allowance-content.js') }}}
{{{ include('models\housing-allowance-calculation.js') }}}
{{{ include('models\housing-allowance-validation.js') }}}
{{{ include('models\housing-allowance-constant.js') }}}
{{{ include('models\housing-allowance-form-config.js') }}}
{{{ include('models\housing-allowance-grid-config.js') }}}
{{{ include('models\housing-allowance-mapper.js') }}}

{{{ include('services\housing-allowance.js') }}}