{{{ include("../js/controllers/bdgt-propertychart.js") }}}
{{{ include("controllers/property-chart.spec.js") }}}

{{{ include("../js/models/property-chart-list-actions.js") }}}
{{{ include("models/property-chart-list-actions.spec.js") }}}
{{{ include("../js/models/property-chart-list-config.js") }}}
{{{ include("models/property-chart-list-config.spec.js") }}}
{{{ include("../js/models/property-chart-notifications.js") }}}
{{{ include("models/property-chart-notifications.spec.js") }}}
{{{ include("../js/models/property-chart.js") }}}
{{{ include("models/property-chart.spec.js") }}}
{{{ include("../js/services/propertychart.js") }}}
{{{ include("services/property-chart.spec.js") }}}



