//  Common Workspace - Models

{{{ include("models/workspace-table.js") }}}
//{{{ include("models/workspace-details-nav.js") }}}
//{{{ include("models/workspace-details-date-range.js") }}}
{{{ include("models/workspace-view.js") }}}

//  Common Workspace - Controllers

{{{ include("controllers/workspaces.js") }}}

//  Common Workspace - Templates

{{{ include("templates/workspace-table.js") }}}

//  Common Workspace - Directives

{{{ include("directives/workspace-table.js") }}}
