{{{ include("../../../_common/standalone/js/data/page-state.js") }}}


{{{ include("controllers/job-position-details.js") }}}

{{{ include("models/job-position-details.js") }}}
{{{ include("models/job-position-form-config.js") }}}
{{{ include("models/job-position-state.js") }}}

{{{ include("services/job-position-details.js") }}}
{{{ include("services/translator.js") }}}

{{{ include("data/job-position-details-mock-data.js") }}}
{{{ include("data/job-position-list-mock-data.js") }}}
