{{{ include("../../../_common/standalone/js/data/page-state.js") }}}

// Models
{{{ include("models/contract.js") }}}
{{{ include("models/contract-form-config.js") }}}
{{{ include("models/vendor-list.js") }}}
{{{ include("models/autocomplete.js") }}}
{{{ include("models/search-text.js") }}}

// Services
{{{ include("services/contract.js") }}}
{{{ include("services/contract-notifs.js") }}}
{{{ include("services/contract-validation.js") }}}
{{{ include("services/date-util.js") }}}
{{{ include("services/translator.js") }}}
{{{ include("services/vendor-list.js") }}}

// Controllers

{{{ include("controllers/contract-define.js") }}}