{{{ include("../js/models/manage-gl-actionslist.js") }}}
{{{ include("models/manage-gl-actionslist-spec.js") }}}

{{{ include("../js/models/manage-gl-createupdategl.js") }}}
{{{ include("models/manage-gl-createupdategl-spec.js") }}}

{{{ include("../js/models/manage-gl-edit-save-gl.js") }}}
{{{ include("models/manage-gl-edit-save-gl-spec.js") }}}

{{{ include("../js/models/manage-gl-notifications.js") }}}
{{{ include("models/manage-gl-notifications-spec.js") }}}

{{{ include("../js/models/manage-gl-error-handling.js") }}}
{{{ include("models/manage-gl-error-handling-spec.js") }}}

{{{ include("../js/models/manage-gl-account.js") }}}
{{{ include("models/manage-gl-account-spec.js") }}}

{{{ include("../js/controllers/bdgt-manage-gl-account.js") }}}
{{{ include("controllers/bdgt-manage-gl-account-spec.js") }}}

{{{ include("../js/models/manage-grid.js") }}}
{{{ include("models/manage-grid-spec.js") }}}

{{{ include("../js/models/manage-gl-grid-factory.js") }}}
{{{ include("models/manage-gl-grid-factory-spec.js") }}}


{{{ include("../js/services/manage-gl-account.js") }}}
{{{ include("services/manage-gl-account-spec.js") }}}
