// RealPage Common

{{{ include("../../lib/realpage/common/js/scripts.js") }}}

// RealPage Modules

{{{ include("../../lib/realpage/actions-menu/js/scripts.js") }}}
{{{ include("../../lib/realpage/authorization/js/scripts.js") }}}

{{{ include("../../lib/realpage/busy-indicator/js/scripts.js") }}}
{{{ include("../../lib/realpage/collapsible-list/js/scripts.js") }}}
{{{ include("../../lib/realpage/complex-grid/js/scripts.js") }}}
{{{ include("../../lib/realpage/date-range/js/scripts.js") }}}
{{{ include("../../lib/realpage/datepicker/js/scripts.js") }}}
{{{ include("../../lib/realpage/draggable/js/scripts.js") }}}
{{{ include("../../lib/realpage/droppable/js/scripts.js") }}}
{{{ include("../../lib/realpage/expandable-list/js/scripts.js") }}}
{{{ include("../../lib/realpage/float-scroll/js/scripts.js") }}}
{{{ include("../../lib/realpage/form-input-date/js/scripts.js") }}}
{{{ include("../../lib/realpage/form-input-text-v1/js/scripts.js") }}}
{{{ include("../../lib/realpage/form-textarea-v1/js/scripts.js") }}}
{{{ include("../../lib/realpage/form-select-menu-v1/js/scripts.js") }}}
{{{ include("../../lib/realpage/form-track-changes/js/scripts.js") }}}
{{{ include("../../lib/realpage/global-header/js/scripts.js") }}}
{{{ include("../../lib/realpage/grid/js/scripts.js") }}}
{{{ include("../../lib/realpage/grid-controls/js/scripts.js") }}}
{{{ include("../../lib/realpage/inline-dialog/js/scripts.js") }}}
{{{ include("../../lib/realpage/language/js/scripts.js") }}}
{{{ include("../../lib/realpage/notifications/js/scripts.js") }}}
{{{ include("../../lib/realpage/page-title/js/scripts.js") }}}
{{{ include("../../lib/realpage/pagination/js/scripts.js") }}}
{{{ include("../../lib/realpage/popover/js/scripts.js") }}}
{{{ include("../../lib/realpage/primary-nav/js/scripts.js") }}}
{{{ include("../../lib/realpage/property-picker/js/scripts.js") }}}
{{{ include("../../lib/realpage/scrolling-tabs-menu/js/scripts.js") }}}
{{{ include("../../lib/realpage/session-info/js/scripts.js") }}}
{{{ include("../../lib/realpage/slide-toggle/js/scripts.js") }}}
{{{ include("../../lib/realpage/tabs-menu/js/scripts.js") }}}
{{{ include("../../lib/realpage/toggle/js/scripts.js") }}}
{{{ include("../../lib/realpage/workspaces/js/scripts.js") }}}
{{{ include("../../lib/realpage/datetimepicker-v1/js/scripts.js") }}}


// Budgeting Modules

{{{ include("base/_bundle.inc") }}}
{{{ include("config/_bundle.inc") }}}
{{{ include("controllers/_bundle.inc") }}}
{{{ include("templates/templates.inc.js") }}}

{{{ include('../../_common/standalone/js/models/budget-driver-access.js') }}}
{{{ include('../../_common/standalone/js/models/budget-model-details.js') }}}
{{{ include('../../_common/standalone/js/services/budget-model-details.js') }}}
{{{ include('../../_common/standalone/js/services/workflow-level.js') }}}
{{{ include('../../_common/breadcrumbs/js/components/breadcrumbs.js') }}}
{{{ include('../../_common/breadcrumbs/js/providers/breadcrumbs.js') }}}