{{{ include('models/recall-dist-allocations-model.js') }}}
{{{ include('models/recall-dist-allocations-config.js') }}}
{{{ include('models/recall-dist-allocations-content.js') }}}
{{{ include('models/recall-dist-allocations-error-handling.js') }}}

{{{ include('templates/confirm-modal.js') }}}

{{{ include('services/budget-allocation-recall-svc.js') }}}

{{{ include('controllers/recall-dist-allocation.js') }}}
