{{{ include('controllers\salary.js') }}}

{{{ include('models\salary.js') }}}
{{{ include('models\salary-content.js') }}}
{{{ include('models\salary-calculation.js') }}}
{{{ include('models\salary-validation.js') }}}
{{{ include('models\salary-constant.js') }}}
{{{ include('models\salary-form-config.js') }}}
{{{ include('models\salary-grid-config.js') }}}
{{{ include('models\salary-mapper.js') }}}

{{{ include('services\salary.js') }}}